// Code generated by protoc-gen-go. DO NOT EDIT.
// source: int64.proto

package null

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// String is a nullable string. It supports SQL and JSON serialization.
type Int64 struct {
	I                    int64    `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64) Reset()         { *m = Int64{} }
func (m *Int64) String() string { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()    {}
func (*Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b67b79850cd447c, []int{0}
}

func (m *Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64.Unmarshal(m, b)
}
func (m *Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64.Marshal(b, m, deterministic)
}
func (m *Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64.Merge(m, src)
}
func (m *Int64) XXX_Size() int {
	return xxx_messageInfo_Int64.Size(m)
}
func (m *Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int64 proto.InternalMessageInfo

func (m *Int64) GetI() int64 {
	if m != nil {
		return m.I
	}
	return 0
}

func (m *Int64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Int64)(nil), "profbiss.null.Int64")
}

func init() { proto.RegisterFile("int64.proto", fileDescriptor_8b67b79850cd447c) }

var fileDescriptor_8b67b79850cd447c = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcc, 0x2b, 0x31,
	0x33, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x28, 0xca, 0x4f, 0x4b, 0xca, 0x2c,
	0x2e, 0xd6, 0xcb, 0x2b, 0xcd, 0xc9, 0x51, 0xd2, 0xe6, 0x62, 0xf5, 0x04, 0xc9, 0x0a, 0xf1, 0x70,
	0x31, 0x66, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31, 0x66, 0x0a, 0x89, 0x70, 0xb1, 0x96,
	0x25, 0xe6, 0x64, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x04, 0x41, 0x38, 0x4e, 0x6c, 0x51,
	0x2c, 0x20, 0x4d, 0x49, 0x6c, 0x60, 0xa3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x0f,
	0x86, 0x5a, 0x59, 0x00, 0x00, 0x00,
}
